apiVersion: v1
kind: Service
metadata:
  name: postgres-service
  labels:
    app: postgres
spec:
  type: NodePort
  ports:
  - port: 5432
    nodePort: 30390
    targetPort: 5432
    protocol: TCP
  selector:
   app: postgres